#!/usr/bin/env bash
source $(dirname $0)/generic_wrapper.sh
if [[ -v KOGIA_BCFTOOLS_TAG ]]
then
  gen_docker bschiffthaler/bcftools:$KOGIA_BCFTOOLS_TAG $@
else
  gen_docker bschiffthaler/bcftools:latest $@
fi