#!/usr/bin/env bash
source $(dirname $0)/generic_wrapper.sh
if [[ -v KOGIA_BEDTOOLS_TAG ]]
then
  gen_docker bschiffthaler/bedtools:$KOGIA_BEDTOOLS_TAG $@
else
  gen_docker bschiffthaler/bedtools:latest $@
fi