#!/usr/bin/env bash
source $(dirname $0)/generic_wrapper.sh
if [[ -v KOGIA_CD_HIT_EST_TAG ]]
then
  gen_docker bschiffthaler/cd-hit-est:$KOGIA_CD_HIT_EST_TAG $@
else
  gen_docker bschiffthaler/cd-hit-est:latest $@
fi
