#!/usr/bin/env bash
source $(dirname $0)/generic_wrapper.sh
if [[ -v KOGIA_CUTADAPT_TAG ]]
then
  gen_docker bschiffthaler/cutadapt:$KOGIA_CUTADAPT_TAG $@
else
  gen_docker bschiffthaler/cutadapt:latest $@
fi
