#!/usr/bin/env bash
source $(dirname $0)/generic_wrapper.sh
if [[ -v KOGIA_DEMULTIPLEX_TAG ]]
then
  gen_docker bschiffthaler/demultiplex:$KOGIA_DEMULTIPLEX_TAG $@
else
  gen_docker bschiffthaler/demultiplex:latest $@
fi
