#!/usr/bin/env bash
source $(dirname $0)/generic_wrapper.sh
if [[ -v KOGIA_DIAMOND_TAG ]]
then
  gen_docker bschiffthaler/diamond:$KOGIA_DIAMOND_TAG $@
else
  gen_docker bschiffthaler/diamond:latest $@
fi