#!/usr/bin/env bash
source $(dirname $0)/generic_wrapper.sh
if [[ -v KOGIA_FASTQC_TAG ]]
then
  gen_docker bschiffthaler/fastqc:$KOGIA_FASTQC_TAG $@
else
  gen_docker bschiffthaler/fastqc:latest $@
fi