#!/usr/bin/env bash
source $(dirname $0)/generic_wrapper.sh
if [[ -v KOGIA_JELLYFISH_TAG ]]
then
  gen_docker bschiffthaler/gffread:$KOGIA_JELLYFISH_TAG $@
else
  gen_docker bschiffthaler/jellyfish:latest $@
fi
