#!/usr/bin/env bash
source $(dirname $0)/generic_wrapper.sh
if [[ -v KOGIA_KALLISTO_TAG ]]
then
  gen_docker bschiffthaler/kallisto:$KOGIA_KALLISTO_TAG $@
else
  gen_docker bschiffthaler/kallisto:latest $@
fi