#!/usr/bin/env bash
source $(dirname $0)/generic_wrapper.sh
if [[ -v KOGIA_MULTIQC_TAG ]]
then
  gen_docker bschiffthaler/multiqc:$KOGIA_MULTIQC_TAG $@
else
  gen_docker bschiffthaler/multiqc:latest $@
fi