#!/usr/bin/env bash
source $(dirname $0)/generic_wrapper.sh
if [[ -v KOGIA_SORTMERNA_TAG ]]
then
  gen_docker bschiffthaler/sortmerna:$KOGIA_SORTMERNA_TAG $@
else
  gen_docker bschiffthaler/sortmerna:latest $@
fi