#!/usr/bin/env bash
source $(dirname $0)/generic_wrapper.sh
if [[ -v KOGIA_SPADES_TAG ]]
then
  gen_docker bschiffthaler/spades:$KOGIA_SPADES_TAG $@
else
  gen_docker bschiffthaler/spades:latest $@
fi