#!/usr/bin/env bash
source $(dirname $0)/generic_wrapper.sh
if [[ -v KOGIA_TRIMMOMATIC_TAG ]]
then
  gen_docker bschiffthaler/trimmomatic:$KOGIA_TRIMMOMATIC_TAG $@
else
  gen_docker bschiffthaler/trimmomatic:latest $@
fi