#!/usr/bin/env bash
source $(dirname $0)/generic_wrapper.sh
if [[ -v KOGIA_WTDBG2_TAG ]]
then
  gen_docker bschiffthaler/wtdbg2:$KOGIA_WTDBG2_TAG $@
else
  gen_docker bschiffthaler/wtdbg2:latest $@
fi